services:
  backend:
    build: ./backend
    container_name: node-api
    ports:
      - 5050:5050
    networks:
      - devops_network
    environment:
      DB_STRING: ${db_string}  
    depends_on:
      - mongodb

  frontend:
    build: ./frontend/todo
    container_name: react-frontend
    ports:
      - 5173:5173 
    networks:
      - devops_network
    depends_on:
      - backend
    # environment:
    #   REACT_APP_API_URL: http://backend:5050 

  mongodb:
    image: mongo:latest  
    container_name: mongodb-db
    ports:
      - 27017:27017
    networks:
      - devops_network
    # volumes:
    #   - mongo-data:/data/db  

networks:
  devops_network:
    driver: bridge 

# volumes:
#   mongo-data:
#     driver: local  # Persist MongoDB data locally