# services:
#   backend:
#     # image: sarthakb413/mern-todo-backend:latest
#     build: ./backend
#     container_name: node-api
#     ports:
#       - 5050:5050
#     networks:
#       - devops_network
#     environment:
#       DB_STRING: ${db_string}  
#     depends_on:
#       - mongodb

#   frontend:
#     # image: sarthakb413/mern-todo-frontend:latest
#     build: ./frontend/todo
#     container_name: react-frontend
#     ports:
#       - 5173:5173 
#     networks:
#       - devops_network
#     depends_on:
#       - backend


#   mongodb:
#     image: mongo:latest  
#     container_name: mongodb-db
#     ports:
#       - 27017:27017
#     networks:
#       - devops_network  

# networks:
#   devops_network:
#     driver: bridge 



# # services:
# #   backend:
# #     image: sarthakb413/mern-todo-backend:latest
# #     container_name: node-api
# #     ports:
# #       - 5050:5050
# #     networks:
# #       - devops_network
# #     environment:
# #       DB_STRING: ${db_string}  
# #     depends_on:
# #       - mongodb

# #   frontend:
# #     image: sarthakb413/mern-todo-frontend:latest
# #     container_name: react-frontend
# #     ports:
# #       - 5173:5173 
# #     networks:
# #       - devops_network
# #     depends_on:
# #       - backend


# #   mongodb:
# #     image: mongo:latest  
# #     container_name: mongodb-db
# #     ports:
# #       - 27017:27017
# #     networks:
# #       - devops_network  

# # networks:
# #   devops_network:
# #     driver: bridge


services:
  backend:
    image: sarthakb413/mern-todo-backend:latest
    container_name: node-api
    networks:
      - devops_network
    environment:
      DB_STRING: ${db_string}
    depends_on:
      - mongodb

  frontend:
    image: sarthakb413/mern-todo-frontend:latest
    container_name: react-frontend
    networks:
      - devops_network
    depends_on:
      - backend

  mongodb:
    image: mongo:latest
    container_name: mongodb-db
    ports:
      - 27017:27017
    networks:
      - devops_network

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - 80:80
    networks:
      - devops_network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

networks:
  devops_network:
    driver: bridge